### ISSUE TITLE
Integration testing with CMIP data

### ISSUE THREAD

**Issue by mandresm** [esm-tools/pymor#67]
We need some integration testing for the CI where we actually CMORize a portion of a CMIP dataset, that has been already CMORized and compared against it, making sure that our output is good.

**Comment by pgierz** [comment]
I'm using the example as it currently is in `main`. Here is the current comparison.

On levante, make sure one has ncdump available before:
```
$ module load netcdf-c
```

A CMORized file has the following header information:
```
$ ncdump -h /pool/data/CMIP6/data/CMIP/AWI/AWI-CM-1-1-MR/piControl/r1i1p1f1/Omon/thetao/gn/v20181218/thetao_Omon_AWI-CM-1-1-MR_piControl_r1i1p1f1_gn_240101-241012.nc
netcdf thetao_Omon_AWI-CM-1-1-MR_piControl_r1i1p1f1_gn_240101-241012 {
dimensions:
        time = UNLIMITED ; // (120 currently)
        bnds = 2 ;
        ncells = 830305 ;
        depth = 46 ;
        vertices = 16 ;
variables:
        double time(time) ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:bounds = "time_bnds" ;
                time:units = "days since 2401-1-1 00:00:00" ;
                time:calendar = "standard" ;
                time:axis = "T" ;
        double time_bnds(time, bnds) ;
        double depth(depth) ;
                depth:long_name = "depth" ;
                depth:units = "m" ;
                depth:positive = "down" ;
                depth:axis = "Z" ;
        float thetao(time, depth, ncells) ;
                thetao:units = "degC" ;
                thetao:CDI_grid_type = "unstructured" ;
                thetao:_FillValue = 1.e+30f ;
                thetao:missing_value = 1.e+30f ;
                thetao:description = "Diagnostic should be contributed even for models using conservative temperature as prognostic field." ;
                thetao:coordinates = "lat lon" ;
                thetao:standard_name = "sea_water_potential_temperature" ;
                thetao:cell_methods = "area: mean where sea time: mean" ;
                thetao:cell_measures = "area: areacello volume: volcello" ;
        double lat(ncells) ;
                lat:units = "degrees_north" ;
                lat:standard_name = "latitude" ;
                lat:bounds = "lat_bnds" ;
        double lat_bnds(ncells, vertices) ;
        double lon(ncells) ;
                lon:units = "degrees_east" ;
                lon:standard_name = "longitude" ;
                lon:bounds = "lon_bnds" ;
        double lon_bnds(ncells, vertices) ;

// global attributes:
                :frequency = "mon" ;
                :activity_id = "CMIP" ;
                :Conventions = "CF-1.7 CMIP-6.2" ;
                :creation_date = "2018-12-18T12:00:00Z" ;
                :data_specs_version = "01.00.27" ;
                :experiment = "piControl" ;
                :experiment_id = "piControl" ;
                :forcing_index = 1 ;
                :further_info_url = "https://furtherinfo.es-doc.org/CMIP6.AWI.AWI-CM-1-1-MR.piControl.none.r1i1p1f1" ;
                :grid = "FESOM 1.4 (unstructured grid in the horizontal with 830305 wet nodes; 46 levels; top grid cell 0-5 m)" ;
                :grid_label = "gn" ;
                :initialization_index = 1 ;
                :institution = "Alfred Wegener Institute, Helmholtz Centre for Polar and Marine Research, Am Handelshafen 12, 27570 Bremerhaven, Germany" ;
                :institution_id = "AWI" ;
                :license = "CMIP6 model data produced by Alfred Wegener Institute, Helmholtz Centre for Polar and Marine Research, Am Handelshafen 12, 27570 Bremerhaven, Germany is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file). The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." ;
                :mip_era = "CMIP6" ;
                :nominal_resolution = "25 km" ;
                :physics_index = 1 ;
                :product = "model-output" ;
                :realization_index = 1 ;
                :realm = "ocean" ;
                :source = "AWI-CM-1-1-MR" ;
                :source_id = "AWI-CM-1-1-MR" ;
                :source_type = "AOGCM" ;
                :sub_experiment = "none" ;
                :sub_experiment_id = "none" ;
                :table_id = "Omon" ;
                :tracking_id = "hdl:21.14100/1136987e-4237-49a9-9f9f-3f733af0f53d" ;
                :variable_id = "thetao" ;
                :variant_label = "r1i1p1f1" ;
                :branch_method = "standard" ;
                :branch_time_in_child = 0. ;
                :branch_time_in_parent = 182622. ;
                :parent_activity_id = "CMIP" ;
                :parent_experiment_id = "piControl-spinup" ;
                :parent_mip_era = "CMIP6" ;
                :parent_source_id = "AWI-CM-1-1-MR" ;
                :parent_time_units = "days since 1901-1-1" ;
                :parent_variant_label = "r1i1p1f1" ;
}
```

Still in the queue: Our produced files (as of [a3b7088](https://github.com/esm-tools/pymorize/commit/a3b70887b30b51ec101580c732e932c2038dfae8))
```
$ ncdump -h ...
```

**Comment by pgierz** [comment]
# Checklist
## Dimensions
+ [ ] Time is wrong, should be unlimited
+ [ ] Bounds not included
+ [ ] No depths (See #77 for a possible fix)
+ [ ] No vertices
## Variables: 
+ [ ] Time is wrong
+ [ ] No depth (See #77)
+ [ ] Attributes of main variable only partially applied
+ [ ] Lat/lon missing
## Global:
+ [ ] All missing (see #23)

**Comment by pgierz** [comment]
For depth, #77 seems to work with some minor tweaking for mesh caching:
```
$ ncdump -h thetao_Omon_AWI-ocean_piControl_r1i1p1f1_gn_269002-269101.nc
netcdf thetao_Omon_AWI-ocean_piControl_r1i1p1f1_gn_269002-269101 {
dimensions:
        time = 12 ;
        depth = 46 ;
        ncells = 126859 ;
variables:
        float thetao(time, depth, ncells) ;
                thetao:_FillValue = NaNf ;
                thetao:description = "thetao interpolated to FESOM levels" ;
                thetao:grid_type = "unstructured" ;
                thetao:units = "degC" ;
        int64 time(time) ;
                time:units = "days since 2690-02-15 00:00:00.000000" ;
                time:calendar = "standard" ;
        double depth(depth) ;
                depth:_FillValue = NaN ;
                depth:units = "m" ;
                depth:long_name = "depth" ;
                depth:positive = "down" ;
                depth:axis = "Z" ;
        int64 ncells(ncells) ;
}
```

**Comment by pgierz** [comment]
> About missing Lat/lon information, is `pymorize.setgrid.setgrid` function included in the pipeline?

No, I'll add that now. It also isn't in the default pipeline (yet? maybe it shouldn't be a default?)

**Comment by pgierz** [comment]
With #109, time also works for:
* `UNLIMITED`
* datatype `double`
```
$ ncdump -h thetao_Omon_AWI-ocean_piControl_r1i1p1f1_gn_269002-269101.nc
netcdf thetao_Omon_AWI-ocean_piControl_r1i1p1f1_gn_269002-269101 {
dimensions:
        time = UNLIMITED ; // (12 currently)
        depth = 46 ;
        ncells = 126859 ;
variables:
        float thetao(time, depth, ncells) ;
                thetao:_FillValue = NaNf ;
                thetao:description = "thetao interpolated to FESOM levels" ;
                thetao:grid_type = "unstructured" ;
                thetao:units = "degC" ;
        double time(time) ;
                time:_FillValue = NaN ;
                time:units = "days since 2690-02-15 00:00:00.000000" ;
                time:calendar = "standard" ;
        double depth(depth) ;
                depth:_FillValue = NaN ;
                depth:units = "m" ;
                depth:long_name = "depth" ;
                depth:positive = "down" ;
                depth:axis = "Z" ;
        int64 ncells(ncells) ;
}
```
In CMORized files, it was:
```
        double time(time) ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:bounds = "time_bnds" ;
                time:units = "days since 2401-1-1 00:00:00" ;
                time:calendar = "standard" ;
                time:axis = "T" ;
```
Still missing:
* `bounds`
* `standard_name` and `long_name`
* `axis`

For now, I will add those directly in the corrections to time axis for the same part as unlimited settings.

**Comment by pgierz** [comment]
The attributes on `time`, except for bounds, now looks good. Maybe still need to remove `_FillValue` and see what the axis is wrong (starting in February?)
```
netcdf thetao_Omon_AWI-ocean_piControl_r1i1p1f1_gn_269002-269101 {
dimensions:
        time = UNLIMITED ; // (12 currently)
        depth = 46 ;
        ncells = 126859 ;
variables:
        float thetao(time, depth, ncells) ;
                thetao:_FillValue = NaNf ;
                thetao:description = "thetao interpolated to FESOM levels" ;
                thetao:grid_type = "unstructured" ;
                thetao:units = "degC" ;
        double time(time) ;
                time:_FillValue = NaN ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:axis = "T" ;
                time:units = "days since 2690-02-15 00:00:00.000000" ;
                time:calendar = "standard" ;
        double depth(depth) ;
                depth:_FillValue = NaN ;
                depth:units = "m" ;
                depth:long_name = "depth" ;
                depth:positive = "down" ;
                depth:axis = "Z" ;
        int64 ncells(ncells) ;
}
```

**Comment by pgierz** [comment]
Only remaining difference for `time` is now `time_bnds` and the actual timestamps:
Ours:
```
dimensions:
        time = UNLIMITED ; // (12 currently)

variables:
        double time(time) ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:axis = "T" ;
                time:units = "days since 2690-02-15 00:00:00.000000" ;
                time:calendar = "standard" ;
```

Theirs:
```
variables:
        double time(time) ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:bounds = "time_bnds" ;
                time:units = "days since 2401-1-1 00:00:00" ;
                time:calendar = "standard" ;
                time:axis = "T" ;

**Comment by pgierz** [comment]
Next "easy one": For lat/lon, I enabled the set grid step together with a CDO-capable file used for FESOM grids:

```diff
diff --git a/examples/sample.yaml b/examples/sample.yaml
index 763bbee..2402164 100644
--- a/examples/sample.yaml
+++ b/examples/sample.yaml
@@ -18,12 +18,16 @@ pymorize:
   # You can add your own path to the dimensionless mapping table
   # If nothing is specified here, it will use the built-in one.
   # dimensionless_mapping_table: ../data/dimensionless_mappings.yaml
+inherit:
+  mesh_path: /pool/data/AWICM/FESOM1/MESHES/core/
+  grid_file: /pool/data/AWICM/FESOM1/MESHES/core/griddes.nc
 rules:
   - name: paul_example_rule
     description: "You can put some text here"
     inputs:
       - path: /work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/outdata/fesom
         pattern: thetao_fesom_269.*nc
+    # mesh_path: /pool/data/AWICM/FESOM1/MESHES/core/
     cmor_variable: thetao
     model_variable: thetao
     output_directory: .
@@ -39,6 +43,9 @@ pipelines:
       - "pymorize.generic.get_variable"
       - "pymorize.timeaverage.compute_average"
       - "pymorize.units.handle_unit_conversion"
+      # NOTE(PG): Not sure about the order of the next two....
+      - "pymorize.setgrid.setgrid"
+      - "pymorize.fesom_1p4.nodes_to_levels"
       - "pymorize.generic.trigger_compute"
       - "pymorize.generic.show_data"
       - "pymorize.files.save_dataset"
```

However, the output shows no results for lat/lon information:
```
netcdf thetao_Omon_AWI-ocean_piControl_r1i1p1f1_gn_269002-269101 {
dimensions:
        time = UNLIMITED ; // (12 currently)
        depth = 46 ;
        ncells = 126859 ;
variables:
        float thetao(time, depth, ncells) ;
                thetao:_FillValue = NaNf ;
                thetao:description = "thetao interpolated to FESOM levels" ;
                thetao:grid_type = "unstructured" ;
                thetao:units = "degC" ;
        double time(time) ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:axis = "T" ;
                time:units = "days since 2690-02-15 00:00:00.000000" ;
                time:calendar = "standard" ;
        double depth(depth) ;
                depth:_FillValue = NaN ;
                depth:units = "m" ;
                depth:long_name = "depth" ;
                depth:positive = "down" ;
                depth:axis = "Z" ;
        int64 ncells(ncells) ;
}
```

I added some extra debugging output into the setgrid step:

```
Starting setgrid step
    * Using gridfile='/pool/data/AWICM/FESOM1/MESHES/core/griddes.nc'
    * Determined required_dims as required_dims={'ncells'}
    * After inspection, can_merge=False
WARNING: !!! SETGRID Step was requested by nothing to be merged! Check carefully!
```

A ncdump of the grid-file shows:
```
netcdf griddes {
dimensions:
        ncells = 126859 ;
        vertices = 18 ;
        nlinks_max = 9 ;
        Three = 3 ;
        ntriags = 244660 ;
        nlev = 46 ;
variables:
        double lon(ncells) ;
                lon:units = "degrees_east" ;
                lon:standard_name = "longitude" ;
                lon:bounds = "lon_bnds" ;
        double lon_bnds(ncells, vertices) ;
                lon_bnds:units = "degrees_east" ;
                lon_bnds:standard_name = "longitude_bounds" ;
                lon_bnds:centers = "lon" ;
        double lat(ncells) ;
                lat:units = "degrees_north" ;
                lat:standard_name = "latitude" ;
                lat:bounds = "lat_bnds" ;
        double lat_bnds(ncells, vertices) ;
                lat_bnds:units = "degrees_north" ;
                lat_bnds:standard_name = "latitude_bounds" ;
                lat_bnds:centers = "lat" ;
        double cell_area(ncells) ;
                cell_area:units = "m2" ;
                cell_area:_FillValue = -1. ;
                cell_area:long_name = "area of grid cell" ;
                cell_area:grid_type = "unstructured" ;
                cell_area:coordinates = "lat lon" ;
        int node_node_links(ncells, nlinks_max) ;
                node_node_links:_FillValue = -1 ;
                node_node_links:long_name = "Indicates which other nodes neighbour each node." ;
        int triag_nodes(ntriags, Three) ;
                triag_nodes:_FillValue = -1 ;
                triag_nodes:long_name = "Maps every triangular face to its three corner nodes." ;
        int coast(ncells) ;
                coast:_FillValue = -1 ;
                coast:long_name = "Indicates coastal nodes: coast=1, internal=0" ;
                coast:grid_type = "unstructured" ;
                coast:coordinates = "lat lon" ;
        double depth(nlev) ;
                depth:units = "m" ;
                depth:_FillValue = -1. ;
                depth:long_name = "depth of model levels in metres (positive downwards)" ;
        int depth_lev(ncells) ;
                depth_lev:_FillValue = -1 ;
                depth_lev:long_name = "depth in terms of number of active levels beneath each ocean surface grid point" ;
                depth_lev:grid_type = "unstructured" ;
                depth_lev:coordinates = "lat lon" ;

// global attributes:
                :Conventions = "CF-1.4" ;
                :history = "Grid description file generated with spheRlab sl.grid.writeCDO" ;
}
```

I would have expected it to do something similar to `cdo setgrid`:
```
$ cdo -setgrid,/pool/data/AWICM/FESOM1/MESHES/core/griddes.nc thetao_Omon_AWI-ocean_piControl_r1i1p1f1_gn_269002-269101.nc tmp.nc
cdo    setgrid: Processed 70026168 values from 1 variable over 12 timesteps [2.36s 99MB].
$ ncdump -h tmp.nc
netcdf tmp {
dimensions:
        time = UNLIMITED ; // (12 currently)
        ncells = 126859 ;
        vertices = 18 ;
        depth = 46 ;
variables:
        double time(time) ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:units = "days since 2690-02-15 00:00:00.000000" ;
                time:calendar = "standard" ;
                time:axis = "T" ;
        double lon(ncells) ;
                lon:standard_name = "longitude" ;
                lon:long_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:bounds = "lon_bnds" ;
        double lon_bnds(ncells, vertices) ;
        double lat(ncells) ;
                lat:standard_name = "latitude" ;
                lat:long_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:bounds = "lat_bnds" ;
        double lat_bnds(ncells, vertices) ;
        double depth(depth) ;
                depth:long_name = "depth" ;
                depth:units = "m" ;
                depth:positive = "down" ;
                depth:axis = "Z" ;
        float thetao(time, depth, ncells) ;
                thetao:units = "degC" ;
                thetao:CDI_grid_type = "unstructured" ;
                thetao:coordinates = "lat lon" ;
                thetao:_FillValue = NaNf ;
                thetao:missing_value = NaNf ;
                thetao:description = "thetao interpolated to FESOM levels" ;

// global attributes:
                :CDI = "Climate Data Interface version 2.0.5 (https://mpimet.mpg.de/cdi)" ;
                :Conventions = "CF-1.6" ;
                :history = "Thu Feb 20 18:19:43 2025: cdo -setgrid,/pool/data/AWICM/FESOM1/MESHES/core/griddes.nc thetao_Omon_AWI-ocean_piControl_r1i1p1f1_gn_269002-269101.nc tmp.nc" ;
                :CDO = "Climate Data Operators version 2.0.5 (https://mpimet.mpg.de/cdo)" ;
}
```

**Comment by pgierz** [comment]
With #111, the metadata in the variables is also nearly complete. Still need a sensible _FillValue.

**Ours**
```
        float thetao(time, depth, ncells) ;
                thetao:_FillValue = NaNf ;
                thetao:description = "thetao interpolated to FESOM levels" ;
                thetao:grid_type = "unstructured" ;
                thetao:units = "degC" ;
                thetao:standard_name = "sea_water_potential_temperature" ;
                thetao:long_name = "Sea Water Potential Temperature" ;
                thetao:cell_methods = "area: mean where sea time: mean" ;
                thetao:cell_measures = "area: areacello volume: volcello" ;
                thetao:coordinates = "lat lon" ;
```

**Theirs**
```
        float thetao(time, depth, ncells) ;
                thetao:units = "degC" ;
                thetao:CDI_grid_type = "unstructured" ;
                thetao:_FillValue = 1.e+30f ;
                thetao:missing_value = 1.e+30f ;
                thetao:description = "Diagnostic should be contributed even for models using conservative temperature as prognostic field." ;
                thetao:coordinates = "lat lon" ;
                thetao:standard_name = "sea_water_potential_temperature" ;
                thetao:cell_methods = "area: mean where sea time: mean" ;
                thetao:cell_measures = "area: areacello volume: volcello" ;
```

**Comment by pgierz** [comment]
This issue still needs to be addressed before I give a version 1.0.0

**Comment by pgierz** [comment]
I still have "time bounds not included" on the checklist at the top of the issue, but I would say we close it for now and make a separate issue to track that after the workshop.
